service:
  name: serverless-dynamo

plugins:
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: build/handler.hello
    events:
      - http:
          method: get
          path: hello
