version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:stretch
    steps:
        - checkout
        - run: sudo npm i -g serverless
        - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install
        - run: yarn
        - run: yarn run test
        - run: npm run ci:deploy